<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Assignment 2 Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>df9cbd78-e850-4e21-a968-0181f6a30691</testSuiteGuid>
   <testCaseLink>
      <guid>d393e640-3c0c-40dd-8630-26b9c92cdcc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Assignment_2/2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1127e55e-cbb2-4d2e-865b-5191285361b3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/assignment_2_testdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55c01465-7f37-4e6c-b2a9-d772beef408b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6dabaab-f38f-4b9b-9eb8-4d8b9f848259</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d11b994-ab4b-44dc-a6cb-cfb846cf5b03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aa419e3-d1f7-424c-8ff3-b57941eff57a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f4c18a5-680b-444f-9f44-2235b12606c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37330cd1-48b6-4813-afb5-894af0ba1a8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f0d7fc-e495-41cc-899c-89577ea6bc59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1127e55e-cbb2-4d2e-865b-5191285361b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>222e92a5-5f67-4e01-a46a-4838a3e80c6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1127e55e-cbb2-4d2e-865b-5191285361b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>105e66cf-1751-4742-8bfd-149283e3d250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1127e55e-cbb2-4d2e-865b-5191285361b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5b5c16c4-dffe-4de4-abbb-ba5933bd1fbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38c2653a-f978-4963-aa36-7f6f57617c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Assignment_2/1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6807422c-7872-4fd7-be71-48a340c7128e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed2fdcb6-8396-4ce8-9f56-4892997276c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34200d24-f089-4344-84da-0dfd7aa6f242</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f4440e7-adb9-4fda-9f01-5db3210509bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Assignment_2/3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eb93a20-d7e0-4c29-8059-9e01a67608fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90e57755-4f14-4f00-881b-2406d24b2b75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77f16c3c-afa0-4cf1-ab53-95f705ec8638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab6b7682-81af-4b59-96c1-a0da8b4a2522</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2631c63a-75e5-4503-88b1-cae0413dc462</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/buttons</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9a1cf42-e904-465f-8f88-07aff60c37a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43d63f07-3842-4e01-b5d4-daf6ae272f4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de7a3682-e23a-4d7c-b4c1-88f2b7e0d639</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd847835-9492-483b-b024-3aef1e8359dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec2c510d-ef5b-4c1b-b338-cc29e6908d55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60f46e34-c9e0-43d4-aed8-58d5d9e83c4b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
