<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toast</name>
   <tag></tag>
   <elementGuidId>365d3c58-2d2f-4f13-a5a9-e37f9068ded9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header/div[@id='navbar']/div[@id='nav-main']/div[1]/div[1]/div[1]/div[3]/span[1]/span[1]/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
