<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Visual feedback_demo-frame</name>
   <tag></tag>
   <elementGuidId>cea66f27-da0b-488a-814a-f5ee5f8df7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.demo-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d2bc1064-dd04-4e7f-82e4-72c2d2130a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/demos/droppable/default.html</value>
      <webElementGuid>41ec60f3-66d3-425c-949a-95573366dafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-frame</value>
      <webElementGuid>64d24e14-e073-45c2-bc1e-855dfb813fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/iframe[@class=&quot;demo-frame&quot;]</value>
      <webElementGuid>82f35372-fb94-44fe-8e42-c00f1f8d2c7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/iframe</value>
      <webElementGuid>438eb512-c807-4e8d-b07b-2b0f3a75a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b6fcc4ca-a356-4bbc-861e-a22c8003dedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/resources/demos/droppable/default.html']</value>
      <webElementGuid>16429023-4b66-4657-995e-f1317ffc160b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
