<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upload</name>
   <tag></tag>
   <elementGuidId>7b1eac8c-b1b5-43b5-98e7-d36831cee7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/app-filemanagement[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
