<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ui-slider-handle ui-corner-all ui-state-default ui-state-hover ui-state-focus</name>
   <tag></tag>
   <elementGuidId>6b58739c-c123-4c4b-82ce-0cc0f7eca79e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-slider-handle.ui-corner-all.ui-state-default.ui-state-hover.ui-state-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slider']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66c2096e-5cc7-4b1d-b654-f231da9dfbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd02e0ba-69c7-4537-aad1-9ea13e1f362f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-slider-handle ui-corner-all ui-state-default ui-state-hover ui-state-focus</value>
      <webElementGuid>0221bfa4-e463-4c89-a9e5-14dd7bf7d6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider&quot;)/span[@class=&quot;ui-slider-handle ui-corner-all ui-state-default ui-state-hover ui-state-focus&quot;]</value>
      <webElementGuid>69dc60ba-ece6-4492-8799-d63abdc68207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Slider  jQuery UI/iframe_Vertical slider_demo-frame</value>
      <webElementGuid>b42c1356-75e8-4efa-92f3-1a8760863fd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider']/span</value>
      <webElementGuid>9a35d5f2-ae30-4caa-9e44-783ec9e2cfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>8cd04cfb-c540-4498-bb25-a2a8ff521cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
